### ISSUE TITLE
[Bug]: The application doesn't perform as expected

### ISSUE THREAD

**Issue by APrabhu21** [andsfonseca/dota2-rpc-client#1]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

Installed following steps but nothing happened

### Expected Behavior

Expected it to show hero in discord activity status

### Steps To Reproduce

uh just installed it by double clicking install.windows.bat and pressing space once it said press any key in the cmd window

**Comment by andsfonseca** [comment]
Hello @APrabhu21, thanks for testing the application.

Could you check some things for me?

After confirming the application installation, could you open the task manager and check if this service is running?

![image](https://user-images.githubusercontent.com/7833466/172992237-1a20bd3c-3ae0-4eab-9887-353d9a927816.png)

**Comment by galax-debug** [comment]
Same for me :/

**Comment by APrabhu21** [comment]
hey ithe service is working
[image: image.png]

**Comment by andsfonseca** [comment]
> Same for me :/

Could you perform the same test mentioned above?

**Comment by andsfonseca** [comment]
@APrabhu21, if it's running normally, check for me if the service was able to create the file "file.exe" in this specific folder of dota files.

![image](https://user-images.githubusercontent.com/7833466/173005324-aee01974-baab-4f11-bb84-27156e4ef31b.png)

The content of this file is this:

```
"dota2-rpc-client Configuration"
{
    "uri"               "http://127.0.0.1:52424/"
    "timeout"           "5.0"
    "buffer"            "0.1"
    "throttle"          "0.1"
    "heartbeat"         "30.0"
    "data"
    {
        "provider"      "1"
        "map"           "1"
        "player"        "1"
        "hero"          "1"
        "draft"         "1"
        "wearables"     "1"
    }
    "auth"
    {
        "token"         "518quwZuBDWr"
    }
}
```

**Comment by APrabhu21** [comment]
theres no file with thatname in that folder

**Comment by andsfonseca** [comment]
> theres no file with thatname in that folder

There seems to be an error creating the file.

I will upload the file for you to literally put inside the folder, let me know if this works correctly after that.

[gamestate_integration_rpc.zip](https://github.com/andsfonseca/dota2-rpc-client/files/8876419/gamestate_integration_rpc.zip)

Alternatively, I'll create a debug version. In case you want to help me look at this problem more closely.

**Comment by APrabhu21** [comment]
i put the file it still didnt work

**Comment by APrabhu21** [comment]
do i have to set it up in discord too or something

**Comment by andsfonseca** [comment]
> do i have to set it up in discord too or something

In Discord, make sure this option is enabled.

![image](https://user-images.githubusercontent.com/7833466/173007950-6b97d96c-a2af-4960-be20-ec716dfe2cc3.png)

**Comment by APrabhu21** [comment]
![image](https://user-images.githubusercontent.com/101726062/173008281-b9d843b6-e23a-4383-bf85-f1abc822f65c.png)
it still only shows normal dota while im in demo mode

**Comment by andsfonseca** [comment]
I just uploaded a debug version from this link.

https://github.com/andsfonseca/dota2-rpc-client/releases/download/v1.0.2/dota2-rpc-client-debug.zip

Can you unzip the file, open the terminal in the current folder and then type the following command:

```
dota2-rpc-client -f
```

Give me the output of the program. Expected is to have this output:

![image](https://user-images.githubusercontent.com/7833466/173009396-c5cff3e4-cef9-4f9a-b4db-72e23c6eb884.png)

**Comment by APrabhu21** [comment]
any specific place to unzip it or wherever

**Comment by APrabhu21** [comment]
ah i misclicked
and closed it

**Comment by andsfonseca** [comment]
> any specific place to unzip it or wherever

wherever, just be careful not to delete the files later

**Comment by APrabhu21** [comment]
![image](https://user-images.githubusercontent.com/101726062/173010089-e3f514cb-3170-4f9b-a5ee-33cbc0cedb93.png)
it shows me this error message

**Comment by andsfonseca** [comment]
I'm sorry about that, for some reason I thought you would have the development package installed on your machine. It's looking for Microsoft Visual C++ v140 Debug on your system.

Does the same error happen with the release version?

**Comment by APrabhu21** [comment]
it doesnt show any errors with the release version

**Comment by andsfonseca** [comment]
Can you run this same command in the release version?

```
dota2-rpc-client -f
```

**Comment by APrabhu21** [comment]
i ran that command and it executed as well but it still doesnt show whats expected in activity status
c) Microsoft Corporation. All rights reserved.

E:\Tools\dc rich>dota2-rpc-client -f
dota2rpc started
\Unable to find DotA 2 files! Please create the following file with the name 'gamestate_integration_rpc.cfg' and insert it into the folder '{{STEAM_LIBRARY_PATH}}/dota 2 beta/game/dota/cfg/gamestate_integration/'.

=========== gamestate_integration_rpc.cfg ================
"dota2-rpc-client Configuration"
{
    "uri"               "http://127.0.0.1:52424/"
    "timeout"           "5.0"
    "buffer"            "0.1"
    "throttle"          "0.1"
    "heartbeat"         "30.0"
    "data"
    {
        "provider"      "1"
        "map"           "1"
        "player"        "1"
        "hero"          "1"
        "draft"         "1"
        "wearables"     "1"
    }
    "auth"
    {
        "token"         "518quwZuBDWr"
    }
}
==========================================================

Listening at http://127.0.0.1:52424.
Press Ctrl+C twice to exit.
|




heres whats in the cmd window rn

**Comment by andsfonseca** [comment]
This is the standard response when it fails to create the integration file automatically. It's a good sign actually.

Let's do one more test.

Uninstall the service, if you have it installed;
Manually copy the cfg file to your Dota 2 folder;
Close dota 2;
Run the program using the command (Do not close the terminal);
Open dota and enter the hero demo

**Comment by APrabhu21** [comment]
it still only shows as playing dota 2

**Comment by APrabhu21** [comment]
it says unable to find dota2 files at the top in cmd window

**Comment by APrabhu21** [comment]
oh it worked the problme was i was directly putting the cfg file in the cfg folder while i had to create gamestate_integration folder and put it inside that. Sorry it was my fault

**Comment by andsfonseca** [comment]
Nice! Put a print here with your favorite hero so I can check if everything is ok.

**Comment by APrabhu21** [comment]
![image](https://user-images.githubusercontent.com/101726062/173018265-4d3ddce4-1fc0-4a51-b826-afcc0248b091.png)
here you go

**Comment by andsfonseca** [comment]
Perfect, let me know if you find any more problems.
I will try to improve this installation process later.

Then try to install again, so you don't have to keep opening the terminal every time.

I don't participate much in the reddit community but if you find someone with a similar problem can you ask them to check this issue?

**Comment by APrabhu21** [comment]
Sure i can do that

**Comment by HyunJae5463** [comment]
The Service is running and the gamestate_integration Folder exist but it still only shows Playing Dota 2
Tried to reinstall and PC but doesnt change anything
Using dota2-rpc-client -f gives same result as from the other dude in this thread

**Comment by andsfonseca** [comment]
Hello @HyunJae5463, thx for use 

Can you perform some tasks for me?

* First uninstall the service if you have it installed.
* Open the terminal in the application folder and enter the following command:
```
dota2-rpc-client -f
```
* Close and Open Dota 2 and enter the demo
* Send me the output of the program.

**Comment by phola123** [comment]
@andsfonseca hope you are supporting this project. 
I tried running it but its not showing in discord.
-Files are created 
-Service is running (tried restarting it)
- "-f" command in terminal shows me failed to update status.

**Comment by andsfonseca** [comment]
Hello @phola123, let's test a few things.

1. Go to your discord and make sure the option to display game activity is enabled and then restart discord.
2. Check if the service is working. To do this, just open the task manager and go to the services tab. Look for a service called dota2-rpc and check if it is running
3. Restart the service. (Or start if off)
4. Restart Dota.
5. Open a test map or a game with bots and check if discord has updated your profile

If nothing happened anyway.

6. Stop the service in the task manager.
7. Open the terminal with the command "-f", as you did before
8. Open a test map or a game with bots and send me some screenshots of the terminal.

**Comment by phola123** [comment]
![image](https://user-images.githubusercontent.com/26165786/196052136-675aaefe-178e-452f-b57d-1e8879371b0c.png)
in test map with bots shows nothing

**Comment by andsfonseca** [comment]
It seems to be something related to discord.

I'll take a look and see if I can find out what's going on.

Recently the Discord SDK was updated, maybe something related to this.

I'll add some error messages related to discord connection failure instead of just a failure message.

Not very related, one user said he was able to run the app using administrative privileges. See #20.

I'll create a more specific issue for this.

**Comment by firelordgukki** [comment]
the dota2-rpc-client are quickly opening a terminal and closed quickly without starting the client, couldn't find the rpc on "detail" task manager, and the .bat shows this image <img width="616" height="91" alt="Image" src="https://github.com/user-attachments/assets/48cd44c3-a16a-40a2-a6c2-afa44b7d1e81" />

**Comment by andsfonseca** [comment]
Hello @firelordgukki,

To run in live mode, use:

```
dota2-rpc-client.exe -r
```

Make sure to open the terminal in the folder where the file is being stored.

**Comment by firelordgukki** [comment]
tried that and got this problem?? <img width="1098" height="300" alt="Image" src="https://github.com/user-attachments/assets/6a33a352-3f62-4006-8dfa-c145bc2da325" />

**Comment by andsfonseca** [comment]
Sorry, @firelordgukki. Is "-f".

![Image](https://github.com/user-attachments/assets/1059a50c-71de-4607-9fad-9f2ad1fc4516)

**Comment by firelordgukki** [comment]
able to do that, but .bat still have the same response. did restarting the discord, game and everything. is there anything that i miss ?

> the dota2-rpc-client are quickly opening a terminal and closed quickly without starting the client, couldn't find the rpc on "detail" task manager, and the .bat shows this image <img alt="Image" width="616" height="91" src="https://private-user-images.githubusercontent.com/270942933/569100268-48cd44c3-a16a-40a2-a6c2-afa44b7d1e81.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQ0NTQyNjcsIm5iZiI6MTc3NDQ1Mzk2NywicGF0aCI6Ii8yNzA5NDI5MzMvNTY5MTAwMjY4LTQ4Y2Q0NGMzLWExNmEtNDBhMi1hNmMyLWFmYTQ0YjdkMWU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMyNVQxNTUyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Q3NzYxYzYyNWYyYmE4NjIzMTM0ODUyZDMwN2Y2YWYxOWU4OTM2MWZiNzQ5ZjI0ZTE3NzNkOTVjYTJhM2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Anm6RKdsMpl04lH45YysmBDQmQZKm-u6S1TXbKZdw68">

**Comment by andsfonseca** [comment]
Try installing using the alternative method:

```
.\dota2-rpc-client.exe -i
```

<img width="857" height="200" alt="Image" src="https://github.com/user-attachments/assets/f91c4e23-0066-4d7c-8c67-16061eb9347d" />

Then, check the services.msc. Try to find dota

<img width="556" height="615" alt="Image" src="https://github.com/user-attachments/assets/334131d6-7941-44b1-9d50-bb6ec27cb7bd" />
