### ISSUE TITLE
[Feature]: Add Team names for watching DPC matches

### ISSUE THREAD

**Issue by mikqsq** [andsfonseca/dota2-rpc-client#18]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the solution you'd like

I am not sure it is possible to do. Add Team names in the discord for watching DPC matches when spectating a DPC game. Since TI is coming soon, it is a nice discord status to show if you are watching TI. 
e.g.
Watching OG vs PSG.LGD | TI 2022
Radiant 3k | Dire
20:00 elapsed

or 

The International 2022
Watching OG vs PSG.LGD 
Radiant 3k | Dire
20:00 elapsed

Just a suggestion. Not sure it is possible to do.

**Comment by andsfonseca** [comment]
I'll see if that's possible. But team information isn't available that easily.

Some possible solutions could be: Comparing the match ID with information from Liquipedia or getting the player's team name. But I'll search

**Comment by andsfonseca** [comment]
Hello @mikqsq, sorry for the delay.

Unfortunately the dota client does not expose the names of the teams that are playing using the Game Integration service.

I researched how to get this information from DPC teams and the only place I could get this detailed information was from the Liquipedia website.

One strategy would be to get the steam ids of the players and compare them with the information on the site and then put the names of the teams. But for that, it would be necessary to consume an API or perform a Web Scraping that identifies the teams from the players' ids.

I believe this feature could be added in the future if there is an easier way to get this information.

I'll be on the lookout for projects that retrieve information from the professional dota league (if it takes too long I might even create a project that does that). But for now, I won't be able to add this feature.

**Comment by mikqsq** [comment]
Hi @andsfonseca , no worry. It is understandable. I thought game client would expose team names and stuffs because they have built-in DPC standings and supporter fantasy stuffs inside the client. It is ok if there is no easy way to do it.
