### ISSUE TITLE
dota2 rpc  service not appearing in task bar after installation

### ISSUE THREAD

**Issue by isfuuu** [andsfonseca/dota2-rpc-client#19]
Its just not there i tried everything uninstall/reinstall copy cfg files but the service isnt running at all

**Comment by andsfonseca** [comment]
Hello @isfuuu, thx for trying to use the application.

The application is not a desktop application but a service, so it will only appear in the taskbar if you open it using the terminal.

You can check as follows: open the task manager and look for the services tab; check if the dota2rpc executable is registered in the services tab and is running.

You can also run it manually, open the terminal in the folder where you installed the application and run the commands:

To install:

```shell
dota2-rpc-client.exe -i
```

To run:

```shell
dota2-rpc-client.exe -f
```

Try running one of these and show the result here, it can be a print if you want
