### ISSUE TITLE
[Bug]: Not working as intended - SOLVED

### ISSUE THREAD

**Issue by GTPang** [andsfonseca/dota2-rpc-client#2]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

Did all the steps mentioned in the website, But Discord is not showing Game Activity, 
Its Not working. 

### Dota 2 Patch

7.31d

**Comment by GTPang** [comment]
**Solution**: I followed these steps

> Let's do one more test.
> 
> Uninstall the service, if you have it installed; Manually copy the cfg file to your Dota 2 folder; Run the program using the command (Do not close the terminal); Open dota and enter the hero demo
> 
> The file is here: [#1 (comment)](https://github.com/andsfonseca/dota2-rpc-client/issues/1#issuecomment-1152026794)

Source: https://github.com/andsfonseca/dota2-rpc-client/issues/1

**Comment by andsfonseca** [comment]
@GTPang. I'm glad you found the solution in the previous thread. As it's still a basic version, the installation process is still a bit confusing.

Later, send us a print so we can see you with your favorite hero.

If you encounter any more problems, just let me know. I'll try to answer as soon as possible.

**Comment by GTPang** [comment]
![image](https://user-images.githubusercontent.com/21367947/173118812-4782401e-a29f-47e7-9909-864dc37d8205.png)
Hi, So I played the game later but it was not working so I had to follow the steps to start it again, maybe look into what the problem is, I will be happy to help.l

**Comment by andsfonseca** [comment]
Thx @GTPang, help and suggestions are always welcome.
