### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by asphodelius** [andsfonseca/dota2-rpc-client#20]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

i followed these steps 

1. Uninstall the service, if you have it installed;
2. Manually copy the cfg file to your Dota 2 folder;
3. Run the program using the command (Do not close the terminal);
4. Open dota and enter the hero demo 

and got this in console
![image](https://user-images.githubusercontent.com/50658938/180595890-9c2a2b01-cd40-4999-a47c-31b9d7bce94a.png)

### Dota 2 Patch

7.31d

**Comment by asphodelius** [comment]
solve it 
apparently when u open discord as administrator u need to open `dota2-rpc-client.exe` as admin too

**Comment by andsfonseca** [comment]
Hello @asphodelius , thanks for using the application, sometimes the application fails to find DiscordD for some reasons: either "Discord" is not open or the application does not have sufficient permission.

I'm glad you found the solution. After, put a screenshot here to see if everything is working normally.

**Comment by asphodelius** [comment]
Works perfectly, you did a great job
![image](https://user-images.githubusercontent.com/50658938/180652083-470470c3-7b36-474d-a24e-ebf9c31d63b2.png)
