### ISSUE TITLE
[Bug]: Service fails to run

### ISSUE THREAD

**Issue by leamare** [andsfonseca/dota2-rpc-client#22]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

D2RPC Client service either 
- fails to install (on a new machine)
- runs for a while and crashes (on a machine which had previous installation of D2RPC)

### Expected Behavior

Service installs and runs.

### Steps To Reproduce

Try to run the install and run the service

### Anything else?

This only happened with 1.0.4 version.
1.0.3 doesn't have this issue.

**Comment by andsfonseca** [comment]
Hi @leamare , thanks for continuing the tests.

Can u make some prints?

Uninstalls both services for me on both computers.

Can you try to install using commands instead of using scripts?

```shell
dota2-rpc-client -i
```

If you can send a print of the output of each computer so we can try to find the error during the installation.

**Comment by leamare** [comment]
It produces either no output or it's no different from the regular install. The only difference is that it hangs up after service install on the latest version.

**Comment by andsfonseca** [comment]
The installation process and service start process are now separate.

If there was no way out, then it seems that everything went well. But to be sure, check if the "gamestate_integration_rpc" file was created in the "{SteamLibrary}\dota 2 beta\game\dota\cfg\gamestate_integration" folder.

If everything is ok, let's continue. Open task manager and stop the dota2rpc service (if it is not already stopped).

Run in the terminal by the command below

```shell
dota2-rpc-client -f
```
Open the dota, test a hero and check for me if there was any output different from the usual.

**Comment by leamare** [comment]
In case of the old machine (upgrading from an older version), the gamestate_integration_rpc file was already there, and the service was reinstalled, but was just crashing after a while (launching the client with `-f` parameter worked fine). No errors shown or anything. It only started working properly (service started working again) after switching to a previous version.

On the new machine it didn't create config file and service, though it seems to be a separate issue.

**Comment by andsfonseca** [comment]
@leamare, i found a bug in 1.0.4 realease.

I'm going to recreate the 1.0.4 version.

I believe I must have added testing code in the current version.

If possible you can create an issue about the installation process, as they are separate they end up becoming different problems

**Comment by andsfonseca** [comment]
Tente com essa versão rodar a aplicação: https://github.com/andsfonseca/dota2-rpc-client/releases/tag/v1.0.4

**Comment by andsfonseca** [comment]
Try with this version: https://github.com/andsfonseca/dota2-rpc-client/releases/tag/v1.0.4

**Comment by leamare** [comment]
This seems to fix the issue with running the service on 1.0.4.
The installation seems to be indeed a different issue.
