### ISSUE TITLE
[Bug]: Service fails to install

### ISSUE THREAD

**Issue by leamare** [andsfonseca/dota2-rpc-client#23]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

The install script fails to install a service (it doesn't show up in the services list) or add the `gamestate_integration_rpc` config.
Output looks completely normal.

### Expected Behavior

Service installs and runs

### Steps To Reproduce

It happens just while executing the install script as usual.

### Anything else?

Hard to specify the exact reason.
My main PC has two users setup (both have admin privileges), this might be the issue.
Alternatively, I suspect there is some kind of access issue.

Might need to try a debug build with verbose output to figure out what's happening there.

**Comment by leamare** [comment]
Tried versions 1.0.2, 1.0.3, 1.0.4

Version 1.0.2 ended up installing the service/config, but it couldn't run. Running the executable with `-f` flag led to crash with "Failed to debug" error. Non-debug version just ended up crashing silently.

Versions 1.0.3 and 1.0.4 were similar. Install script was running properly, but the service wasn't installed for whatever reason. Launching them with `-f` flag didn't led to any crashes (unsurprisingly), but it didn't seem to connect to the game client.

It doesn't seem like a permissions problem (1.0.2 was able to install, after all), but I suspect there might be a problem with accessing the 52424 port? Not entirely sure.

**Comment by andsfonseca** [comment]
![image](https://user-images.githubusercontent.com/7833466/182739241-5d8d0b13-fefc-45a9-b2b0-cab6617794e3.png)

This is the output when the installation process work. Can you send a picture of the output when you try install?

**Comment by leamare** [comment]
![image](https://user-images.githubusercontent.com/2502223/182929435-acc408f4-76ab-499b-87d4-c91a77617bba.png)

**Comment by andsfonseca** [comment]
@leamare Can you run a trial version on your machine? I created a version with more debug messages.
It won't be necessary to uninstall your current version, just unzip and run.

**Comment by leamare** [comment]
I'll be able to run it tomorrow.

**Comment by andsfonseca** [comment]
[dota-rpc-client-test.zip](https://github.com/andsfonseca/dota2-rpc-client/files/9262948/dota-rpc-client-test.zip)

**Comment by leamare** [comment]
![image](https://user-images.githubusercontent.com/2502223/182964649-af017fba-d238-40e1-917f-ac54112e1019.png)

Seems to be a permission issue after all, though I'm not sure where it could've come from and what folders is it using.

**Comment by andsfonseca** [comment]
Just to be sure, does this error also happen when you run as administrator?

**Comment by andsfonseca** [comment]
I will create an exception handler in case it fails to create the folder or file.

In case of error, manual installation information should appear in the terminal

**Comment by andsfonseca** [comment]
[dota2-rpc-client-test.zip](https://github.com/andsfonseca/dota2-rpc-client/files/9264538/dota2-rpc-client-test.zip)

This version has exception handling. The output will also show which files it tries to write and an error message should be displayed if it fails.

**Comment by leamare** [comment]
> Just to be sure, does this error also happen when you run as administrator?

Yes, I only run it from an admin PShell.

![image](https://user-images.githubusercontent.com/2502223/183110648-2737d59a-959c-4f2e-800b-52cd4bb8c162.png)

Seems like there is the issue. It's trying to create a folder and cfg file in `F:\SteamLibrary\...`
But Dota client is located in `D:\SteamLibrary\...`.

It should probably have some kind of feedback when this happens and also show the path it used.
Changing "STEAM_FOLDER" in the config file doesn't really solve the issue (it's still looking in the wrong library folder).

**Comment by leamare** [comment]
I tried it with the mainline 1.0.4 version.
Changing `STEAM_FOLDER` to `D:\\SteamLibrary` forced it to actually show this prompt:
```
File 'D:\SteamLibrary/SteamApps/libraryfolders.vdf 'not found!
Unable to find 'dota 2 beta' folder using steam library, please set the directory...
```
and allow me to manually select `dota 2 beta` folder.

So it seems to be the issue with the automatic folder detection

In the `libraryfolders.vdf` the "F" drive one comes first, but it doesn't have "570" listed. Only the "D" library folder.

**Comment by andsfonseca** [comment]
You're right!

Can you send me a copy of your libraryfolders.vdf file for me to take a look at. (You can remove some games from your list and your personal information if necessary)

**Comment by leamare** [comment]
Here's the copy

[libraryfolders.vdf.txt](https://github.com/andsfonseca/dota2-rpc-client/files/9270022/libraryfolders.vdf.txt)

**Comment by andsfonseca** [comment]
@leamare, can you test this version?

This is the definitive version, so it is recommended to uninstall the old one if you have it installed.

Link: #24

**Comment by leamare** [comment]
This should do

![image](https://user-images.githubusercontent.com/2502223/183220655-f2fefea7-88a8-47f6-b42e-a22ce58d8ce2.png)

**Comment by andsfonseca** [comment]
Perfect, I hope that's all. Thanks for testing with me.

I will accept the pull request and close the thread. You can reopen if you need.
