### ISSUE TITLE
[Feature]: Disabling smokes/Aghs indicators

### ISSUE THREAD

**Issue by leamare** [andsfonseca/dota2-rpc-client#3]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Smokes and aghs indicators might compromise your team, especially when playing competitive games or being a part of public discord server.

### Describe the solution you'd like

Some kind of config wizard to disable showing these states (for all matches or only for tournament lobbies) or adding a delay.
Disabling KDA/LH/DN counters would be nice as well.

**Comment by leamare** [comment]
> I'm thinking of creating a configuration file where you can choose what you want to be displayed. It sounds like a good idea?
I was thinking about that as well, but for most players who are going to use this, it might be too much already. But having a config file is better than having nothing at all, so I'm onboard with it.

> I'll also research if I can get this setting to automatically activate when you enter Streamer Mode on Discord.
Yeah, this would definitely be a great improvement.

**Comment by andsfonseca** [comment]
Okays, I'll create this functionality. Will be included in the next version
