### ISSUE TITLE
[Bug]: Unable to update discord activity

### ISSUE THREAD

**Issue by andsfonseca** [andsfonseca/dota2-rpc-client#37]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

Described by @phola123 in issue #1.
Unable to update discord state

**Comment by andsfonseca** [comment]
I'll start testing and implementing the requested features. @phola123 , if you can help me test it when it's ready I'd be grateful. I can't reproduce it here :( .

**Comment by phola123** [comment]
sure

**Comment by andsfonseca** [comment]
@phola123, check this version, I put one more debug lines so that when there is an error in discord it shows an error code.

https://github.com/andsfonseca/dota2-rpc-client/files/9840401/dota-2-rpc-client.zip
