### ISSUE TITLE
[Bug]: libdiscord_game_sdk.so

### ISSUE THREAD

**Issue by MarquesGama1401** [andsfonseca/dota2-rpc-client#47]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

when I run the command ./dota2-rpc-client -i or ./dota2-rpc-client , this appears: ./dota2-rpc-client: error while loading shared libraries: libdiscord_game_sdk.so: cannot open shared object file: No such file or directory

### Expected Behavior

I know it's in experimental state but it should work normally

### Dota 2 Patch

the error is not in dota

### Steps To Reproduce

on linux, try running the command ./dota2-rpc-client -i or  ./dota2-rpc-client

### Anything else?

I don't know if it's just me that has this bug

**Comment by MarquesGama1401** [comment]
I already fixed the bugI already fixed the bug , i just downloaded Discord game Sdk v3.2.1 , extract , rename the discord_game_sdk.so file to libdiscord_game_sdk.so and copy it to the /lib/ folder , it worked for me

**Comment by andsfonseca** [comment]
Hello @MarquesGama1401, sorry for the delay.

I'm updating the Discord SDK version, I'll make it available from the next version. Thanks for the tip

**Comment by andsfonseca** [comment]
I would also like to invite you to test the next version when I upload it.
