### ISSUE TITLE
[Bug]: Dont show overlay

### ISSUE THREAD

**Issue by dankYoff** [andsfonseca/dota2-rpc-client#48]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

During installation, I selected the folder where Steam is located, after that I went back into the game and restarted Discord, but the overlay did not appear in Discord

### Steps To Reproduce

1) Install
2) Choose folder for steam
3) Restart game
4) Restart discord
5) Play match

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/213687711-4eae5738-f80b-453c-8188-5290b1f8eaa7.png)

**Comment by andsfonseca** [comment]
Hi @dankYoff. I'm not with my pc right now. But you can send a screenshot of your services in the task manager? Try to find a program named as dota2-rpc.

**Comment by dankYoff** [comment]
task manager has no program dota2-rpc

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/213689130-c18761d0-63af-49d4-81b0-c2b441b8ef3a.png)

**Comment by andsfonseca** [comment]
Try check in services tab. If the app is missing, I believe occurred some problem during the installation process

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/213697936-453b1f24-8683-4795-848b-2e7cca1d5441.png)
say stopped

**Comment by dankYoff** [comment]
i run and this work thanks
