### ISSUE TITLE
[Bug]: Wont show 

### ISSUE THREAD

**Issue by Akarinii** [andsfonseca/dota2-rpc-client#56]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the bug

After running " insta.windows.bat " it installed, can even see in the task manager and its running, but it still wont appear on my discord rich presence. 

### Dota 2 Patch

7.33c

**Comment by andsfonseca** [comment]
Hello @Akarinii  sorry for the delay.

But you can send a screenshot of your services in the task manager? Try to find a program named as dota2-rpc.

**Comment by andsfonseca** [comment]
Strange, it was supposed to be working. If u join a match with bots, does the app still running?
In addition, also check if your discord settings allow the display of rich presence

**Comment by aoisensi** [comment]
Try deleting `cfg` folder.
It work for me.

**Comment by TenseiCho** [comment]
I'm also having the same issue. Shows it services but won't run.

> Try deleting `cfg` folder. It work for me.
Tried but did not work on my end.
