### ISSUE TITLE
[Feature]: Aegis item effect

### ISSUE THREAD

**Issue by mikqsq** [andsfonseca/dota2-rpc-client#8]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the solution you'd like

I think it is neat to have Aegis item effect f you are holding Aegis. The priority of the status should be:

1. Smoked
2. Aegis
3. Aghanim and Shard

### Dota 2 Patch

7.31d

**Comment by andsfonseca** [comment]
Hello @mikqsq, thanks for using the application.

This looks cool, I'm checking if I can see the player's inventory during the match. If I can I'll implement an icon for Aegis
